// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: floor.sql

package db

import (
	"context"
)

const addFloor = `-- name: AddFloor :one
INSERT INTO floor (
    id,
    parking_lot_id
) VALUES (
    $1, $2
) RETURNING id, parking_lot_id
`

type AddFloorParams struct {
	ID           int32  `json:"id"`
	ParkingLotID string `json:"parking_lot_id"`
}

func (q *Queries) AddFloor(ctx context.Context, arg AddFloorParams) (Floor, error) {
	row := q.db.QueryRowContext(ctx, addFloor, arg.ID, arg.ParkingLotID)
	var i Floor
	err := row.Scan(&i.ID, &i.ParkingLotID)
	return i, err
}
